<?php include_once "funciones.php"; ini_set("memory_limit", "-1");
        if (isset($_GET['sl']) and ! empty($_GET['sl'])) {
            $encriptval = $_GET['sl'];
            $decrypted_sol = tools::encrypt_decrypt('decrypt', $encriptval);
            $sql_gensol = "SELECT S.`folio`, S.`descanso`, S.`usuario`, S.`periodo`, S.`vacaciones`, S.`salida`, S.`regreso`, S.`estatus`, S.`fecha` AS registro, U.`usuario` AS empleado, U.`nombre`, U.`ingreso`, U.`empresa` AS cde, P.`periodo` AS persys, P.`dias`, P.`tomados`, P.`pendientes`, P.`vigencia` FROM `vac_solicitud` S INNER JOIN `com_usuarios` U ON S.`usuario` = U.`id` INNER JOIN `vac_periodos` P ON S.`periodo` = P.`id` WHERE S.`id` = " . $decrypted_sol;
            $rs_gensol = mysqli_query($conexion, $sql_gensol);
            $campsol = mysqli_fetch_assoc($rs_gensol);
            $codemp = $campsol['cde'];
            $folsolprnt = $campsol['folio'];
            $emplnom = substr($campsol['empleado'], 2);
            $nmemply = utf8_encode($campsol['nombre']);
            $emplying = $campsol['ingreso'];
            $rgsolusr = $campsol['registro'];
            $usuario = $campsol['empleado'];
            $cadvacs = explode(",", $campsol['vacaciones']);
            $lnsoli = count($cadvacs);
            $cadsal = explode(",", $campsol['salida']);
            $vigsys = explode("-", $campsol['vigencia']);
            $cadreg = explode(",", $campsol['regreso']);
            $daydesc = tools::retornadia($campsol['descanso']);
            $prds = $campsol['persys'];
            $corrdays = $campsol['dias'];
            $disfdays = $campsol['tomados'];
            $dispdays = $campsol['pendientes'];
            $fchvacs = retsolfechas($cadvacs);
            $fchsal = retsolfechas($cadsal);
            $fchreg = retsolfechas($cadreg);
            $sepingusr = explode("-", $emplying);
            $ingresusr = $sepingusr[2] . '/' . tools::obtenermes($sepingusr[1]) . '/' . $sepingusr[0];
            $vacsusr = str_replace(",", " | ", $fchvacs);
            $salsusr = str_replace(",", " | ", $fchsal);
            $regsusr = str_replace(",", " | ", $fchreg);
            $htmlE =''; $header = '<div style="font-size:1.4em; font-weight:900; text-align:center; letter-spacing:0.75px;">' . imprimeempresausr($codemp) . '</div><div style="font-weight:600; font-size:1em; text-align:center; letter-spacing:2.5px;">SOLICITUD DE VACACIONES</div><div style="font-size: 0.95em; font-weight:400; text-align:center;">' . tools::retornadia(date("w")) . ' ' . date("d") . ' de ' . tools::obtenermes(date("m")) . ' de ' . date("Y") . '</div>';
            $htmlE.='<style>div,h4,td,th,tr,strong,p{font-family:freesans;} </style><table width="100%" cellspacing="4" cellpadding="1" style="font-size:0.87em;"><tr><td>Folio: ' . $folsolprnt . '</td><td style="text-align:right;">Registro: ' . $rgsolusr . '</td></tr></table><table width="100%" cellspacing="0" cellpadding="5" style="font-size:0.87em;"><tr style="background-color:seagreen;"><td colspan="3"><strong style="color:#FFFFFF;">DATOS DEL EMPLEADO</strong></td></tr><tr><td width="16%">Empleado: ' . $emplnom . '</td><td width="54%">Nombre: <span style="font-size:0.83em;">' . $nmemply . '</span></td><td style="text-align:right;" width="30%">Puesto: <span style="font-size:0.9em;">' . consultas::printdeppues('pue', $usuario, $codemp) . '</span></td></tr></table><table width="100%" cellspacing="4" cellpadding="1" style="font-size:0.87em;"><tr><td style="text-align: left;">Departamento: <span style="font-size:0.9em;">';
            $htmlE.=consultas::printdeppues('dep', $usuario, $codemp) . '</span></td><td align="center">Ingreso: <span style="font-size:0.95em;">' . $ingresusr . '</span></td><td align="center">Descanso: ' . strtoupper($daydesc) . '</td></tr></table>';
            $htmlE.='<table width="100%" cellpadding="5" style="font-size:0.87em;"><tr><td colspan="3"></td></tr><tr style="background-color:seagreen;"><td colspan="3"><strong style="color:#FFFFFF;">DATOS DEL PERIODO</strong></td></tr><tr><td>Periodo: ' . $prds . '</td><td>Vigencia: ' . $vigsys[2] . '/' . tools::obtenermes($vigsys[1]) . '/' . $vigsys[0] . '</td><td>Dias que le corresponden: ' . $corrdays . '</td></tr><tr><td>Dias disfrutados: ' . $disfdays . '</td><td>Dias disponibles: ' . $dispdays . '</td><td>Dia(s) solicitados: ' . $lnsoli . '</td></tr></table><table width="100%" cellpadding="5" style="font-size:0.87em;"><tr><td colspan="3"></td></tr><tr style="background-color:seagreen;"><td colspan="3"><strong style="color:#FFFFFF;">EXCLUSIVO PARA CAPITAL HUMANO</strong></td></tr></table><table width="100%" cellpadding="5" style="font-size:0.87em;"><tr><td colspan="3">Dia(s) de vacaciones <br><span style="font-size: 0.85em; font-weight: bold; margin-left: 5%; border-bottom:1px dotted #000;">' . $vacsusr . '</span></td></tr><tr><td colspan="3">Fecha(s) de salida <br><span style="font-size: 0.85em; font-weight: bold; margin-left: 5%; border-bottom:1px dotted #000;">' . $salsusr . '</span></td></tr><tr><td colspan="3">Me presento a trabajar <br><span style="font-size: 0.85em; font-weight: bold; margin-left: 5%; border-bottom:1px dotted #000;">' . $regsusr . '</span></td></tr><tr><td colspan="3"></td></tr></table><table align="center" width="99.5%" cellpadding="5" cellspacing="0" style="font-size:0.87em;"><tr style="background-color:seagreen;"><td colspan="3" style="border:0.1pt dotted seagreen;"><strong style="color: #FFFFFF;">OBSERVACIONES</strong></td></tr><tr><td colspan="3" style="height: 130; border:1px;"></td></tr></table>';
            $htmlE.='<p align="justify" style="font-size: 0.85em;">Me comprometo a entregar este formato a capital humano con las firmas de autorizacion o rechazo correspondientes antes de las fechas indicadas de vacaciones.<table width="100%" cellspacing="12" cellpadding="7" style="margin-top:65; font-size:0.87em;"><tr><td colspan="3"></td></tr><tr><td align="center" width="38%"><span style="font-size:0.8em; border-top:1px solid #6E6E6E; border-top-width:1;">' . $nmemply . '</span></td><td width="24%">&nbsp;</td><td align="center" width="38%"><span style="font-size:0.8em; border-top:1px solid #6E6E6E; border-top-width:1;">FIRMA JEFE INMEDIATO</span></td></tr><tr><td colspan="3"></td></tr><tr style="font-size: 0.8em;"><td width="32%">&nbsp;</td><td align="center" width="36%"><span style="font-size:0.8em; border-top:1px solid #6E6E6E; border-top-width:1;">FIRMA GERENTE CAPITAL HUMANO</span></td><td width="32%">&nbsp;</td></tr></table>';
            reportes::GeneraPDF($header, '', $htmlE, $folsolprnt, 'P', 7.5, 7.5, 25.5, 6.5, TRUE);
            mysqli_free_result($rs_gensol);
        } ?>